# Generated by Django 5.1.6 on 2025-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('housing', 'Housing'), ('food', 'Food'), ('transportation', 'Transportation'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('other', 'Other')], max_length=20),
        ),
    ]
