# Generated by Django 5.1.6 on 2025-05-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_budget_period_alter_budget_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Food', 'Food'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Entertainment', 'Entertainment'), ('Shopping', 'Shopping'), ('Other', 'Other')], max_length=20),
        ),
    ]
